// packages/react-ui/src/components/Select/Select.tsx
import React, { useEffect, useRef, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronDown, faChevronUp } from '@fortawesome/pro-regular-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import './Select.css';

export type SelectSize = 'small' | 'medium' | 'large';

export interface SelectOption {
  value: string;
  label: string;
}

export interface SelectProps {
  /**
   * Select options
   */
  options: SelectOption[];
  /**
   * Currently selected value
   */
  value?: string;
  /**
   * Change handler
   */
  onChange?: (value: string) => void;
  /**
   * Placeholder text (shown in empty state)
   * @default 'Lorem ipsum dolor'
   */
  placeholder?: string;
  /**
   * Select size
   * - small: compact size
   * - medium: default size
   * - large: larger size
   * @default 'medium'
   */
  size?: SelectSize;
  /**
   * Left icon (FontAwesome)
   * @default faMessageEdit
   */
  icon?: IconDefinition | null;
  /**
   * Whether the select is disabled
   */
  disabled?: boolean;
  /**
   * Whether the select is readonly (no chevron, not clickable)
   */
  readonly?: boolean;
  /**
   * Additional CSS class
   */
  className?: string;
}

/**
 * Select component from Figma "OneChaps UI kit" - oc-select
 * 
 * Specifications from Figma (2025-12-10):
 * - Font: Hanken Grotesk 14px / 400
 * - States: empty, active, filled, hovered, readonly, disabled, focus
 * - Sizes: small, medium, large
 * - Border radius: 8px
 * - Focus border: #A9C1B8 (1px)
 * 
 * States color mapping:
 * - empty: text #5D7374, icons #445556
 * - active: text #182021, icons #2D393A, chevron-up
 * - filled: text #182021, icons #445556
 * - hovered: text #374648, icons #374648
 * - readonly: text #182021, icons #182021, no chevron
 * - disabled: text #626C84, icons #626C84
 * - focus: text #445556, icons #445556, border #A9C1B8
 */
export const Select: React.FC<SelectProps> = ({
  options,
  value,
  onChange,
  placeholder = 'Lorem ipsum dolor',
  size = 'medium',
  icon = null,
  disabled = false,
  readonly = false,
  className = '',
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [isFocused, setIsFocused] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState<number | null>(null);
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const listRef = useRef<HTMLDivElement | null>(null);

  // Close on click outside
  useEffect(() => {
    const onDocClick = (e: MouseEvent) => {
      const target = e.target as Node | null;
      if (!target) return;
      if (isOpen) {
        if (triggerRef.current && triggerRef.current.contains(target)) return;
        if (listRef.current && listRef.current.contains(target)) return;
        setIsOpen(false);
        setHighlightedIndex(null);
      }
    };
    document.addEventListener('mousedown', onDocClick);
    return () => document.removeEventListener('mousedown', onDocClick);
  }, [isOpen]);

  // When opening, ensure a sensible highlighted index
  useEffect(() => {
    if (isOpen) {
      const selIdx = options.findIndex(o => o.value === value);
      setHighlightedIndex(selIdx >= 0 ? selIdx : 0);
      // scroll highlighted into view
      setTimeout(() => {
        if (highlightedIndex !== null && listRef.current) {
          const el = document.getElementById(`oc-select-option-${highlightedIndex}`);
          el?.scrollIntoView({ block: 'nearest' });
        }
      }, 0);
    } else {
      setHighlightedIndex(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  const baseClass = 'oc-select';
  
  // Determine current state
  const isEmpty = !value;
  const isFilled = !!value && !isOpen;
  const isActive = isOpen;
  
  const classes = [
    baseClass,
    `${baseClass}--${size}`,
    isEmpty && !isOpen && !isFocused && `${baseClass}--empty`,
    isActive && `${baseClass}--active`,
    isFilled && !isFocused && `${baseClass}--filled`,
    isFocused && !disabled && !readonly && `${baseClass}--focus`,
    disabled && `${baseClass}--disabled`,
    readonly && `${baseClass}--readonly`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const handleClick = () => {
    if (disabled || readonly) return;
    setIsOpen(prev => !prev);
  };

  const handleOptionClick = (optionValue: string) => {
    onChange?.(optionValue);
    setIsOpen(false);
  };

  const handleFocus = () => {
    if (!disabled && !readonly) {
      setIsFocused(true);
    }
  };

  const handleBlur = () => {
    // blur handled by click-outside / keyboard escape for more reliable UX
    setIsFocused(false);
  };

  const selectedOption = options.find(opt => opt.value === value);
  const displayText = selectedOption ? selectedOption.label : placeholder;

  return (
    <div className={`${baseClass}-container`}>
      <button
        ref={triggerRef}
        id={`oc-select-trigger-${Math.random().toString(36).slice(2, 9)}`}
        type="button"
        className={classes}
        onClick={handleClick}
        onFocus={handleFocus}
        onBlur={handleBlur}
        disabled={disabled}
        aria-disabled={disabled}
        aria-readonly={readonly}
        aria-expanded={isOpen}
        aria-haspopup="listbox"
        role="combobox"
        onKeyDown={(e) => {
          if (disabled || readonly) return;
          if (e.key === 'ArrowDown') {
            e.preventDefault();
            if (!isOpen) {
              setIsOpen(true);
              setHighlightedIndex(0);
            } else {
              setHighlightedIndex(prev => {
                const next = prev === null ? 0 : Math.min(options.length - 1, prev + 1);
                return next;
              });
            }
          } else if (e.key === 'ArrowUp') {
            e.preventDefault();
            if (!isOpen) {
              setIsOpen(true);
              setHighlightedIndex(options.length - 1);
            } else {
              setHighlightedIndex(prev => {
                const next = prev === null ? options.length - 1 : Math.max(0, prev - 1);
                return next;
              });
            }
          } else if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            if (!isOpen) {
              setIsOpen(true);
              setHighlightedIndex(options.findIndex(o => o.value === value) || 0);
            } else if (highlightedIndex !== null) {
              const opt = options[highlightedIndex];
              handleOptionClick(opt.value);
            }
          } else if (e.key === 'Escape') {
            setIsOpen(false);
            setHighlightedIndex(null);
            triggerRef.current?.focus();
          } else if (e.key === 'Home') {
            e.preventDefault();
            setHighlightedIndex(0);
          } else if (e.key === 'End') {
            e.preventDefault();
            setHighlightedIndex(options.length - 1);
          }
        }}
      >
        {icon && (
          <span className={`${baseClass}__icon-left`}>
            <FontAwesomeIcon icon={icon} />
          </span>
        )}
        
        <span className={`${baseClass}__text`}>
          {displayText}
        </span>
        
        {!readonly && (
          <span className={`${baseClass}__chevron`}>
            <FontAwesomeIcon icon={isOpen ? faChevronUp : faChevronDown} />
          </span>
        )}
      </button>
      {isOpen && !disabled && !readonly && (
        <div
          ref={listRef}
          className={`${baseClass}-dropdown`}
          role="listbox"
          aria-label="Select options"
        >
          {options.map((option, idx) => {
            const isSelected = option.value === value;
            const isHighlighted = highlightedIndex === idx;
            return (
              <div
                key={option.value}
                id={`oc-select-option-${idx}`}
                role="option"
                aria-selected={isSelected}
                className={`${baseClass}-option ${isHighlighted ? `${baseClass}-option--highlighted` : ''} ${isSelected ? `${baseClass}-option--selected` : ''}`}
                onClick={() => handleOptionClick(option.value)}
                onMouseDown={(e) => e.preventDefault()} // Prevent blur on click
                onMouseEnter={() => setHighlightedIndex(idx)}
              >
                {option.label}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

// packages/angular-ui/src/components/select/select.component.ts
import { Component, Input, Output, EventEmitter, HostListener, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';

export type SelectSize = 'small' | 'medium' | 'large';

export interface SelectOption {
  value: string;
  label: string;
}

/**
 * Select component from Figma "OneChaps UI kit" - oc-select
 * 
 * Specifications from Figma (2025-12-10):
 * - Font: Hanken Grotesk 14px / 400
 * - States: empty, active, filled, hovered, readonly, disabled, focus
 * - Sizes: small, medium, large
 * - Border radius: 8px
 * - Focus border: #A9C1B8 (1px)
 * 
 * @example
 * ```html
 * <!-- Basic select -->
 * <oc-select
 *   [options]="options"
 *   [(value)]="selectedValue"
 *   placeholder="Select an option">
 * </oc-select>
 * 
 * <!-- Different sizes -->
 * <oc-select [options]="options" size="small"></oc-select>
 * <oc-select [options]="options" size="medium"></oc-select>
 * <oc-select [options]="options" size="large"></oc-select>
 * 
 * <!-- With icon -->
 * <oc-select 
 *   [options]="options"
 *   icon="fa-solid fa-user"
 *   placeholder="Select user">
 * </oc-select>
 * 
 * <!-- Disabled -->
 * <oc-select [options]="options" [disabled]="true"></oc-select>
 * 
 * <!-- Readonly -->
 * <oc-select [options]="options" [readonly]="true" value="1"></oc-select>
 * ```
 */
@Component({
  selector: 'oc-select',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.css']
})
export class SelectComponent {
  @ViewChild('triggerButton', { static: false }) triggerButton?: ElementRef<HTMLButtonElement>;
  @ViewChild('dropdown', { static: false }) dropdown?: ElementRef<HTMLDivElement>;

  /**
   * Select options
   */
  @Input() options: SelectOption[] = [];

  /**
   * Currently selected value
   */
  @Input() value?: string;

  /**
   * Value change emitter
   */
  @Output() valueChange = new EventEmitter<string>();

  /**
   * Placeholder text (shown in empty state)
   * @default 'Lorem ipsum dolor'
   */
  @Input() placeholder: string = 'Lorem ipsum dolor';

  /**
   * Select size
   * - small: compact size
   * - medium: default size
   * - large: larger size
   * @default 'medium'
   */
  @Input() size: SelectSize = 'medium';

  /**
   * Left icon (Font Awesome class string)
   * @example icon="fa-solid fa-user"
   */
  @Input() icon?: string;

  /**
   * Whether the select is disabled
   */
  @Input() disabled: boolean = false;

  /**
   * Whether the select is readonly (no chevron, not clickable)
   */
  @Input() readonly: boolean = false;

  /**
   * Additional CSS class
   */
  @Input() className?: string;

  // Internal state
  isOpen: boolean = false;
  isFocused: boolean = false;
  highlightedIndex: number | null = null;

  constructor(private elementRef: ElementRef) {}

  get baseClass(): string {
    return 'oc-select';
  }

  get isEmpty(): boolean {
    return !this.value;
  }

  get isFilled(): boolean {
    return !!this.value && !this.isOpen;
  }

  get isActive(): boolean {
    return this.isOpen;
  }

  get classes(): string {
    const base = this.baseClass;
    return [
      base,
      `${base}--${this.size}`,
      this.isEmpty && !this.isOpen && !this.isFocused && `${base}--empty`,
      this.isActive && `${base}--active`,
      this.isFilled && !this.isFocused && `${base}--filled`,
      this.isFocused && !this.disabled && !this.readonly && `${base}--focus`,
      this.disabled && `${base}--disabled`,
      this.readonly && `${base}--readonly`,
      this.className,
    ]
      .filter(Boolean)
      .join(' ');
  }

  get selectedOption(): SelectOption | undefined {
    return this.options.find(opt => opt.value === this.value);
  }

  get displayText(): string {
    return this.selectedOption ? this.selectedOption.label : this.placeholder;
  }

  get iconClasses(): string[] | undefined {
    return this.icon ? this.icon.split(' ') : undefined;
  }

  handleClick(): void {
    if (this.disabled || this.readonly) return;
    this.isOpen = !this.isOpen;
    
    if (this.isOpen) {
      const selIdx = this.options.findIndex(o => o.value === this.value);
      this.highlightedIndex = selIdx >= 0 ? selIdx : 0;
      
      // Scroll to highlighted option
      setTimeout(() => {
        if (this.highlightedIndex !== null && this.dropdown) {
          const optionEl = this.dropdown.nativeElement.querySelector(`[data-index="${this.highlightedIndex}"]`) as HTMLElement;
          optionEl?.scrollIntoView({ block: 'nearest' });
        }
      }, 0);
    } else {
      this.highlightedIndex = null;
    }
  }

  handleOptionClick(optionValue: string): void {
    this.value = optionValue;
    this.valueChange.emit(optionValue);
    this.isOpen = false;
  }

  handleFocus(): void {
    if (!this.disabled && !this.readonly) {
      this.isFocused = true;
    }
  }

  handleBlur(): void {
    this.isFocused = false;
  }

  handleKeyDown(event: KeyboardEvent): void {
    if (this.disabled || this.readonly) return;

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        if (!this.isOpen) {
          this.isOpen = true;
          this.highlightedIndex = 0;
        } else {
          this.highlightedIndex = this.highlightedIndex === null 
            ? 0 
            : Math.min(this.options.length - 1, this.highlightedIndex + 1);
        }
        break;

      case 'ArrowUp':
        event.preventDefault();
        if (!this.isOpen) {
          this.isOpen = true;
          this.highlightedIndex = this.options.length - 1;
        } else {
          this.highlightedIndex = this.highlightedIndex === null 
            ? this.options.length - 1 
            : Math.max(0, this.highlightedIndex - 1);
        }
        break;

      case 'Enter':
      case ' ':
        event.preventDefault();
        if (!this.isOpen) {
          this.isOpen = true;
          this.highlightedIndex = this.options.findIndex(o => o.value === this.value) || 0;
        } else if (this.highlightedIndex !== null) {
          const opt = this.options[this.highlightedIndex];
          this.handleOptionClick(opt.value);
        }
        break;

      case 'Escape':
        this.isOpen = false;
        this.highlightedIndex = null;
        this.triggerButton?.nativeElement.focus();
        break;

      case 'Home':
        event.preventDefault();
        this.highlightedIndex = 0;
        break;

      case 'End':
        event.preventDefault();
        this.highlightedIndex = this.options.length - 1;
        break;
    }
  }

  @HostListener('document:mousedown', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    const target = event.target as Node;
    if (this.isOpen && !this.elementRef.nativeElement.contains(target)) {
      this.isOpen = false;
      this.highlightedIndex = null;
    }
  }

  isOptionHighlighted(index: number): boolean {
    return this.highlightedIndex === index;
  }

  isOptionSelected(option: SelectOption): boolean {
    return option.value === this.value;
  }

  onOptionMouseEnter(index: number): void {
    this.highlightedIndex = index;
  }

  onOptionMouseDown(event: MouseEvent): void {
    // Prevent blur on click
    event.preventDefault();
  }
}

<div class="oc-select-container">
  <button
    #triggerButton
    type="button"
    [class]="classes"
    (click)="handleClick()"
    (focus)="handleFocus()"
    (blur)="handleBlur()"
    (keydown)="handleKeyDown($event)"
    [disabled]="disabled"
    [attr.aria-disabled]="disabled"
    [attr.aria-readonly]="readonly"
    [attr.aria-expanded]="isOpen"
    [attr.aria-haspopup]="'listbox'"
    role="combobox"
  >
    <span *ngIf="icon" [ngClass]="iconClasses?.concat(['oc-select__icon-left'])" class="oc-select__icon-left">
    </span>
    
    <span class="oc-select__text">
      {{ displayText }}
    </span>
    
    <span *ngIf="!readonly" class="oc-select__chevron">
      <i [ngClass]="isOpen ? ['fa-solid', 'fa-chevron-up'] : ['fa-solid', 'fa-chevron-down']"></i>
    </span>
  </button>

  <div
    #dropdown
    *ngIf="isOpen && !disabled && !readonly"
    class="oc-select-dropdown"
    role="listbox"
    [attr.aria-label]="'Select options'"
  >
    <div
      *ngFor="let option of options; let idx = index"
      [attr.data-index]="idx"
      role="option"
      [attr.aria-selected]="isOptionSelected(option)"
      [class]="baseClass + '-option ' + 
               (isOptionHighlighted(idx) ? baseClass + '-option--highlighted ' : '') + 
               (isOptionSelected(option) ? baseClass + '-option--selected' : '')"
      (click)="handleOptionClick(option.value)"
      (mousedown)="onOptionMouseDown($event)"
      (mouseenter)="onOptionMouseEnter(idx)"
    >
      {{ option.label }}
    </div>
  </div>
</div>
