// Documents/galactik/galactik/packages/angular-ui/src/app/components/avatar/avatar.component.ts
import { Component, Input, computed, Signal, effect } from '@angular/core';

type Size = 'sm' | 'md' | 'lg';
type Variant =
  | 'primary' | 'primaryLight' | 'secondary'
  | 'accent' | 'accentSoft' | 'cherry'
  | 'success' | 'warning' | 'info' | 'error'
  | 'indigo' | 'indigoAlt' | 'neutralDark' | 'yellow' | 'cyan';
type Status = 'online' | 'away' | 'busy' | 'offline' | 'none';

@Component({
  selector: 'qa-avatar',
  standalone: true,
  templateUrl: './avatar.component.html',
  styleUrls: ['./avatar.component.scss'],
  host: {
    class: 'qa-avatar',
    role: 'img',
    '[attr.aria-label]': 'ariaLabel()',
    // tailles
    '[class.qa-avatar--sm]': 'size==="sm"',
    '[class.qa-avatar--md]': 'size==="md"',
    '[class.qa-avatar--lg]': 'size==="lg"',
    // variants
    '[class.qa-avatar--primary]': 'variant==="primary"',
    '[class.qa-avatar--primaryLight]': 'variant==="primaryLight"',
    '[class.qa-avatar--secondary]': 'variant==="secondary"',
    '[class.qa-avatar--accent]': 'variant==="accent"',
    '[class.qa-avatar--accentSoft]': 'variant==="accentSoft"',
    '[class.qa-avatar--cherry]': 'variant==="cherry"',
    '[class.qa-avatar--success]': 'variant==="success"',
    '[class.qa-avatar--warning]': 'variant==="warning"',
    '[class.qa-avatar--info]': 'variant==="info"',
    '[class.qa-avatar--error]': 'variant==="error"',
    '[class.qa-avatar--indigo]': 'variant==="indigo"',
    '[class.qa-avatar--indigoAlt]': 'variant==="indigoAlt"',
    '[class.qa-avatar--neutralDark]': 'variant==="neutralDark"',
    '[class.qa-avatar--yellow]': 'variant==="yellow"',
    '[class.qa-avatar--cyan]': 'variant==="cyan"',
  }
})
export class AvatarComponent {
  /** Nom complet → initiales + accessibilité */
  @Input() name?: string;
  /** URL de l’image ; si absent => fallback initiales */
  @Input() src?: string;
  /** Taille */
  @Input() size: Size = 'md';
  /** Variante sémantique */
  @Input() variant: Variant = 'primary';
  /** Pastille de statut */
  @Input() status: Status = 'none';
  /** Texte alternatif (sinon dérivé du nom) */
  @Input() alt?: string;

  initials(): string {
    const n = (this.name ?? '').trim();
    if (!n) return '??';
    const parts = n.split(/\s+/).slice(0, 2);
    const init = parts.map(p => p.charAt(0).toUpperCase()).join('');
    return init || '??';
  }

  ariaLabel(): string {
    return this.alt ?? (this.name ? `Avatar de ${this.name}` : 'Avatar');
  }
}

<div class="qa-avatar__clip">
  <ng-container *ngIf="src; else initialsTpl">
    <img
      class="qa-avatar__img"
      [src]="src"
      [attr.alt]="ariaLabel()"
    />
  </ng-container>
  <ng-template #initialsTpl>
    <span aria-hidden="true">{{ initials() }}</span>
  </ng-template>
</div>

<!-- pastille de statut qui dépasse -->
<span
  *ngIf="status !== 'none'"
  class="qa-avatar__status"
  [ngClass]="{
    'qa-status--online':  status === 'online',
    'qa-status--away':    status === 'away',
    'qa-status--busy':    status === 'busy',
    'qa-status--offline': status === 'offline'
  }"
  aria-hidden="true">
</span>

// Documents/galactik/galactik/packages/react-ui/src/components/Avatar/Avatar.tsx
import React, { ImgHTMLAttributes } from 'react';
import './avatar.css';

type Size = 'sm' | 'md' | 'lg';
type Variant =
  | 'primary' | 'primaryLight' | 'secondary'
  | 'accent' | 'accentSoft' | 'cherry'
  | 'success' | 'warning' | 'info' | 'error'
  | 'indigo' | 'indigoAlt' | 'neutralDark'
  | 'yellow' | 'cyan';

type Status = 'online' | 'away' | 'busy' | 'offline' | 'none';

export interface AvatarProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'size'> {
  /** Nom complet utilisé pour les initiales et l’accessibilité */
  name?: string;
  /** URL de l’image (si vide → fallback initiales) */
  src?: string;
  /** Taille (sm/md/lg) mappée sur --row-h-* */
  size?: Size;
  /** Variante de couleur sémantique */
  variant?: Variant;
  /** Pastille de statut */
  status?: Status;
}

/** Calcule "AB" à partir de "Alice Bob" */
function getInitials(name?: string) {
  if (!name) return '??';
  const parts = name.trim().split(/\s+/).slice(0, 2);
  return parts.map(p => p.charAt(0).toUpperCase()).join('') || '??';
}

export const Avatar: React.FC<AvatarProps> = ({
  name,
  src,
  alt,
  size = 'md',
  variant = 'primary',
  status = 'none',
  className,
  ...imgProps
}) => {
  const initials = getInitials(name);
  const classes = [
    'qa-avatar',
    `qa-avatar--${size}`,
    `qa-avatar--${variant}`,
    className || ''
  ].join(' ').trim();

  // Accessibilité: alt prioritaire, sinon dérivé du nom
  const computedAlt = alt ?? (name ? `Avatar de ${name}` : 'Avatar');

  return (
  <div className={classes} role="img" aria-label={computedAlt}>
    <div className="qa-avatar__clip">
      {src ? (
        <img className="qa-avatar__img" src={src} alt={computedAlt} {...imgProps} />
      ) : (
        <span aria-hidden="true">{initials}</span>
      )}
    </div>

    {status !== 'none' && (
      <span className={['qa-avatar__status', `qa-status--${status}`].join(' ')} aria-hidden="true" />
    )}
  </div>
);
};

export default Avatar;
