// packages/react-ui/src/components/Tag/Tag.tsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import './Tag.css';

// Country codes type for flag support
export type CountryCode = 'FR' | 'US' | 'GB' | 'DE' | 'ES' | 'IT' | 'JP' | 'CN' | 'CA' | 'AU' | 'BR' | 'IN' | 'RU' | 'MX' | 'KR' | 'NL' | 'SE' | 'CH' | 'BE' | 'AT' | 'PL' | 'NO' | 'DK' | 'FI' | 'IE' | 'PT' | 'GR' | 'CZ' | 'HU' | 'RO' | 'BG' | 'HR' | 'SK' | 'SI' | 'LT' | 'LV' | 'EE' | 'LU' | 'MT' | 'CY';

export type TagColor = 'sage' | 'pink' | 'almond' | 'grey' | 'yellow' | 'warning' | 'cherry' | 'success' | 'indigo' | 'info' | 'cyan' | 'error';
export type TagVariant = 'fill' | 'outline';
export type TagSize = 'xsmall' | 'small' | 'medium';

/**
 * Simple flag renderer using country code CSS class
 * This approach doesn't require external library and works with CSS flags
 */
const FlagIcon: React.FC<{ code: CountryCode; className?: string }> = ({ code, className = '' }) => (
  <span className={`flag flag-${code.toLowerCase()} ${className}`} title={code} />
);

export interface TagProps {
  /**
   * Tag color scheme (from Figma oc-tag variants)
   * Colors: sage, pink, almond, grey, yellow, warning, cherry, success, indigo, info, cyan, error
   * @default 'sage'
   */
  color?: TagColor;
  /**
   * Tag variant style
   * - fill: solid background (oc-tag-primary)
   * - outline: border only with colored text (oc-tag-secondary)
   * @default 'fill'
   */
  variant?: TagVariant;
  /**
   * Tag content/label
   */
  children: React.ReactNode;
  /**
   * Size of the tag (from Figma oc-tag component set)
   * - xsmall: 18px height
   * - small: 24px height (default)
   * - medium: 36px height
   * @default 'small'
   */
  size?: TagSize;
  /**
   * FontAwesome icon on the left side
   * Use icons from @fortawesome/pro-regular-svg-icons
   * @example iconLeft={faTag}
   */
  iconLeft?: IconDefinition;
  /**
   * FontAwesome icon on the right side (trailing icon)
   * Use icons from @fortawesome/pro-regular-svg-icons
   * @example iconRight={faChevronDown}
   */
  iconRight?: IconDefinition;
  /**
   * Country flag to display (ISO 3166-1 alpha-2 code)
   * Uses country-flag-icons library
   * @example flag="FR" flag="US" flag="GB"
   */
  flag?: CountryCode;
  /**
   * Additional CSS class
   */
  className?: string;
}

/**
 * Tag component from Figma "OneChaps UI kit"
 * Synchronized via MCP extraction (2025-12-08)
 * 
 * Specifications from Figma oc-tag-primary and oc-tag-secondary:
 * - Fill variant (oc-tag-primary): 37 color + size combinations
 * - Outline variant (oc-tag-secondary): 37 color + size combinations
 * - Sizes: xsmall 18px, small 24px, medium 36px
 * - Colors: sage, pink, almond, grey, yellow, warning, cherry, success, indigo, info, cyan, error
 * - Border radius: 9999px (fully rounded pill)
 */
export const Tag: React.FC<TagProps> = ({
  color = 'sage',
  variant = 'fill',
  children,
  size = 'small',
  iconLeft,
  iconRight,
  flag,
  className = '',
}) => {
  const baseClass = 'oc-tag';
  const classes = [
    baseClass,
    `${baseClass}--${variant}`,
    `${baseClass}--${color}`,
    `${baseClass}--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <span className={classes}>
      {iconLeft && (
        <FontAwesomeIcon icon={iconLeft} className={`${baseClass}__icon ${baseClass}__icon--left`} />
      )}
      {flag && (
        <FlagIcon code={flag} className={`${baseClass}__flag`} />
      )}
      <span className={`${baseClass}__label`}>{children}</span>
      {iconRight && (
        <FontAwesomeIcon icon={iconRight} className={`${baseClass}__icon ${baseClass}__icon--right`} />
      )}
    </span>
  );
};

export default Tag;

// packages/vue-ui/src/components/Tag/Tag.vue
<template>
  <span :class="classes">
    <!-- iconLeft: support both FontAwesome icon defs and string class names -->
    <FontAwesomeIcon
      v-if="iconLeft && !iconLeftIsString"
      :icon="iconLeft"
      class="oc-tag__icon oc-tag__icon--left"
      aria-hidden="true"
    />
    <i
      v-else-if="iconLeft && iconLeftIsString"
      :class="iconLeft"
      class="oc-tag__icon oc-tag__icon--left"
      aria-hidden="true"
    ></i>

    <span v-if="flag" :class="['flag','flag-'+flag.toLowerCase(), 'oc-tag__flag']" aria-hidden="true"></span>

    <span class="oc-tag__label"><slot /></span>

    <FontAwesomeIcon
      v-if="iconRight && !iconRightIsString"
      :icon="iconRight"
      class="oc-tag__icon oc-tag__icon--right"
      aria-hidden="true"
    />
    <i
      v-else-if="iconRight && iconRightIsString"
      :class="iconRight"
      class="oc-tag__icon oc-tag__icon--right"
      aria-hidden="true"
    ></i>
  </span>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import './Tag.css';

type TagColor = 'sage'|'pink'|'almond'|'grey'|'yellow'|'warning'|'cherry'|'success'|'indigo'|'info'|'cyan'|'error';
type TagVariant = 'fill'|'outline';
type TagSize = 'xsmall'|'small'|'medium';

const props = withDefaults(defineProps<{
  color?: TagColor;
  variant?: TagVariant;
  size?: TagSize;
  // allow either FontAwesome icon def (object) or a string class name
  iconLeft?: any | null;
  iconRight?: any | null;
  flag?: string | null;
}>(), {
  color: 'sage',
  variant: 'fill',
  size: 'small',
  iconLeft: null,
  iconRight: null,
  flag: null,
});

const classes = computed(() => {
  const base = 'oc-tag';
  return [base, `${base}--${props.variant}`, `${base}--${props.color}`, `${base}--${props.size}`];
});

const iconLeftIsString = computed(() => typeof props.iconLeft === 'string');
const iconRightIsString = computed(() => typeof props.iconRight === 'string');

// expose FontAwesomeIcon for template usage (imported binding is usable in <script setup>)
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _FontAwesomeIcon = FontAwesomeIcon;
</script>
